### ISSUE TITLE
Slack, Git, 마일스톤, 스프린트, 스크럼

### ISSUE THREAD

**Issue by kbh18** [Yapp-17th/Web_2_Client#1]

**Comment by kbh18** [comment]
테스트

**Comment by kbh18** [comment]
이번주 부터 깃으로 스프린트를 진행합니다. 

오비분들은 이미 알고 있으신지 모르겠네요. 

요번주는 앞으로 사용할 기본적인 툴하고 

로젝트 진행에 쓰이는 애자일 방법론 중에 하나인 스프린트에 대해서 알고 있으면 좋을 것 같아서 해당 링크를 보냅니다. 

이미 알고 있으신 분들은 쓰윽 읽어 보시고 전혀 모르시는 분들은 아래 링크따라 읽거나 개인적으로 구글링 해주시면서 '스프린트', '마일스톤' 등의 용어를 익히시길..! 

Slack : https://ppss.kr/archives/23688

Git : https://tagilog.tistory.com/377

마일스톤 이란 : https://m.blog.naver.com/milestone365/221260939655

스프린트, 스크럼, 애자일  : http://m.blog.daum.net/business101/6989899?tp_nil_a=2

**Comment by voidmatcha** [comment]
![YAPP_web2](https://user-images.githubusercontent.com/16266103/105870267-70fe8f00-603b-11eb-99be-84a002d5d94f.png)
