### ISSUE TITLE
공통 컴포넌트 개발하기 - Input 컴포넌트

### ISSUE THREAD

**Issue by SkynI25** [Yapp-17th/Web_2_Client#11]
## Input 관련 컴포넌트 개발
Input과 관련된 컴포넌트 개발을 담당하게 되어 아래 4가지 요소를 만들 예정
- range bar
- input 입력창
- toggle 버튼
- 체크박스
![image](https://user-images.githubusercontent.com/20556561/96624640-f7724900-1347-11eb-9be4-03ec9c502aac.png)
![image](https://user-images.githubusercontent.com/20556561/96624689-09ec8280-1348-11eb-8110-339e7727048a.png)
![image](https://user-images.githubusercontent.com/20556561/96624705-0e18a000-1348-11eb-80f1-b8ef5a64377f.png)

## 궁금한 것
- 폰트를 어떻게 적용하면 될까?
- 우리 팀의 코드 컨벤션이 어떻게 되고 어떤 요소를 지켜서 짜야할까?

**Comment by voidmatcha** [comment]
- 폰트 적용에 대해서는 제가 미리 작업해 두었습니다. #13 
- 코드 컨벤션은 airbnb style을 따릅니다. 
  - https://github.com/airbnb/javascript

**Comment by SkynI25** [comment]
@dididy 답변해주셔서 감사합니다 :)
