### ISSUE TITLE
master 브랜치로 PR생성시 Storybook 배포 자동화

### ISSUE THREAD

**Issue by voidmatcha** [Yapp-17th/Web_2_Client#18]
- [x] PR시 자동으로 Storybook을 빌드하여 배포하는 gh-action 규칙 추가
- [x] gh-pages에 배포가 되도록 함
https://github.com/storybookjs/storybook-deployer
https://github.com/VibeerCo/storybook-action-example

**Comment by Lavegaa** [comment]
pr을 넣으면 storybook에서 볼 수 있도록 하는건가요?
storybook은 github page로 배포되는방식인가요?

**Comment by voidmatcha** [comment]
@Lavegaa 네 맞습니다. 일단 오늘 자정까지 작업해서 PR 올려둘게요. 현재 리포지토리 권한이 없어서 secrets를 추가할 수 없는 이슈가 있는데 이부분은 YAPP 운영진분들에게 요청해두도록 하겠습니다.

**Comment by voidmatcha** [comment]
좀 더 찾아보니 https://www.learnstorybook.com/intro-to-storybook/react/kr/deploy/ 에서 언급된 Chromatic을 사용하면 굳이 gh-pages를 사용하지 않아도 될 것 같습니다. 일단은 storybook-deployer을 활용해 gh-pages 기반으로 설정해놓겠습니다.
