### ISSUE TITLE
redux관련 createSlice 구조 질문

### ISSUE THREAD

**Issue by Lavegaa** [Yapp-17th/Web_2_Client#19]
redux구조 관련 질문드려요.
기존의 slice.js파일 같은 경우
https://github.com/Yapp-17th/Web_2_Client/blob/ad0e3d58fb4f5e7967968b530d063cb26a854c34/src/store/slice.js#L1-L24
actions와 reducer를 비구조화 할당을 통해 선언하고,
```js
 const { actions, reducer } = createSlice({ 
   name: 'application', 
   initialState: { 
     number: 0, 
  ....
```
reducer와 actions를 export 합니다.
```js
  ....
 export const { setNumber } = actions; 
  
 export const resetNumber = () => (dispatch) => { 
   dispatch(setNumber({ number: 0 })); 
 }; 
  
 export default reducer; 
```
우리가 채택한 기능당 하나의 reducer파일을 만들기 위해서는 다음과 같이 config를 작성해야 합니다.
(https://redux-toolkit.js.org/api/configureStore)
```js
import { configureStore } from '@reduxjs/toolkit'
import todosReducer from './todos/todosReducer'
import visibilityReducer from './visibility/visibilityReducer'

const reducer = {
  todos: todosReducer,
  visibility: visibilityReducer,
}

const store = configureStore({
  reducer
})
```
여기서 문제는 reducer를 비구조화할당 하면서 꺼내주기 때문에 항상 이름이 reducer로 export된다는 점인데요.

그래서 actions와 reducer를 비구조화 할당을 통해 선언하는 방식이 아닌, 
(https://redux-toolkit.js.org/api/createSlice)
```js
import { createSlice } from '@reduxjs/toolkit';

const timeReducer = createSlice({
  name: 'time',
  initialState: {
    time: 0,
  },
  reducers: {
    setTime(state, { payload: { time } }) {
      return {
        ...state,
        time,
      };
    },
  },
});

export const { setTime } = timeReducer.actions;

export const resetTime = () => (dispatch) => {
  dispatch(setTime({ time: 0 }));
};

export default timeReducer.reducer;
```
위와 같이 하나의 변수로 선언 한 뒤 actions와 reducer를 따로 사용하고, 
```js
import { configureStore } from '@reduxjs/toolkit';

// import reducer from './Slice/slice';
import timeReducer from './Time/time';

const reducers = {
  time: timeReducer,
};

const store = configureStore({ reducer: reducers });

export default store;
```
위와 같은 방법으로 config를 설정해주는건 어떤가요? 위와같은 방법으로 작성했을 시 문제없이 작동했습니다.

## 이후 사용법

또한, reducer에 아래와 같이 key (ex: time)을 줬을 때
```js
const reducers = {
  time: timeReducer,
};
```
[   store 이미지   ]
![image](https://user-images.githubusercontent.com/34911173/96396491-5332ba00-1202-11eb-8d56-50421d2729f2.png)
```js
 key: {
   state: example
}
```
와 같이 object형식으로 store에 들어가게 되고, 사용 시
```js
  const timeSelector = useSelector(get('time'));
  function add() {
    dispatch(setTime({ time: timeSelector.time + 1 }));
  }
```
처럼 사용 할 수 있습니다.

혹시 비구조화 할당 방식으로 actions와 reducer를 선언하고, configure에 적용하는 다른방법이 있을까요?

**Comment by Lavegaa** [comment]
현재 위의 본문 아래쪽 사용 부분에서 만들어주신 snippet의 get함수가 에러가 뜨는 상황입니다.
```js
 const timeSelector = useSelector(get('time'));
  function add() {
    dispatch(setTime({ time: timeSelector.time + 1 }));
  }
```
그래서 아래와 같이 직접 store의 state를 불러오고 있습니다.
```js
  const { timeState } = useSelector((state) => ({
    timeState: state.time.time,
  }));
```

**Comment by voidmatcha** [comment]
@Lavegaa 
제가 그당시 오독을 했던 것 같네요. 

> 다른 패턴이 있나 궁금해서 여쭤본거였어요!
저희는 하나의 파일에 하나의 리듀서로 가는걸로 알고있겠습니다!

라고 하셨었는데 말의 문맥을 잘못 파악해서 생각이 바뀌신줄 알았습니다. 그당시에도 말씀해주신대로 기능에 따라 여러 파일로 나눠서 작성해 하나의 파일에 하나의 reducer만 존재하게끔 수정해주시면 좋겠습니다.

짚어주셔서 감사합니다!

그리고 get 함수에 error가 나는 것은 찬호님이 위와같은 의도대로 redux를 수정하셔서 작업하시면서 발생한 상황인가요? 아니면 처음부터 에러가 발생했나요?

**Comment by Lavegaa** [comment]
네네 비구조화할당 없이 위와같은 패턴으로 작성하겠습니다. 나중에 pr넣고 리뷰한번 해봐요!
get함수가 버튼 컴포넌트에서는 잘 적용이 되는데 제가만들고 있는 컴포넌트에서는 안되네요. 버튼 컴포넌트에서는 되는거 확인했습니다. 진행하면서 계속 테스트 해볼게요

**Comment by dididy** [comment]
@Lavegaa 
넵 알겠습니다. 감사합니다!
