### ISSUE TITLE
녹화 기능 구현

### ISSUE THREAD

**Issue by SkynI25** [Yapp-17th/Web_2_Client#36]
## 목표
System audio sound 까지 녹화할 수 있는 방법을 찾는다. (RecordRTC 또는 Web API 사용)

## 해결방법
- ```getUserMedia``` 메소드를 통해 유저 마이크 목소리를 추출
- ```getDisplayMedia``` 메소드를 통해 시스템 사운드를 추출한다.
- 추출한 두 사운드를 합쳐 영상 스트림에 합친다 - ( @sjh2428 )

## 출처
https://stackoverflow.com/questions/42138545/webrtc-mix-local-and-remote-audio-steams-and-record
https://stackoverflow.com/questions/58644808/how-to-get-a-media-stream-of-the-speakers-output-to-transfer-it-over-the-networ
https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture

## 완성코드
- https://github.com/SkynI25/recording_video
- [시연](https://skyni25.github.io/recording_video/)

**Comment by voidmatcha** [comment]
이부분은 getDisplayMedia 만으로 해결 가능하며( 굳이 track을 분리해서 합치는 작업을 거치지 않아도 됩니다. (단, Chrome Tab을 선택하고 Share audio 체크박스를 클릭해야하는 과정이 추가됩니다)

이 부분은 #45 [Custom Hooks](https://github.com/Yapp-17th/Web_2_Client/blob/master/src/hooks/useMediaRecorder.js)에 구현해 놓았습니다.
