### ISSUE TITLE
마감 이후에 할 작업들 정리 

### ISSUE THREAD

**Issue by voidmatcha** [Yapp-17th/Web_2_Client#87]
- [ ] **테스코드 추가**
- [x] #85 
- [x] #78 
- [x] #101 + 반응형 디자인 적용
- [x] [production용 webpack.config.js 생성 및 적용](https://github.com/Yapp-17th/Web_2_Client/pull/23#discussion_r510679037)
- [x] scss를 styled-components의 GlobalStyle로 적용 시도
- [x] 색상에 대한 변수 생성 및 styled-component ThemeProvider로 적용
- [x] 컴포넌트 구조 Atomic Design으로 리펙토링: https://ui.toast.com/weekly-pick/ko_20200213
  - Atom < Molecule < Organism < Component < Template < Page

**Comment by Lavegaa** [comment]
혹시 반응형 디자인 없이 가능할까요 잡을 수 있을만큼만 잡아볼까요..

**Comment by voidmatcha** [comment]
저도 반응형을 고려하면서 작업하다보니 고통받은 부분이 좀 있어서.. 마감까지는 일단 고려 안해도 될 것 같아요!

**Comment by voidmatcha** [comment]
https://github.com/witherview/witherview_frontend/issues/7
